version: "3.7"
services:
    apromore:
        build: .
        image: apromore/apromore:7.6
        container_name: apromore
        volumes:
            - "./Apromore-Assembly/Editor-Repository:/opt/apromore/Editor-Repository"
            - "./Apromore-Assembly/Event-Logs-Repository:/opt/apromore/Event-Logs-Repository"
            - "./Apromore-Assembly/Filestore-Repository:/opt/apromore/Filestore-Repository"
            - "./Apromore-Assembly/Lucene-Repository:/opt/apromore/Lucene-Repository"
        depends_on:
            - mysql-db   
        ports:
            - "9000:9000"
            
    mysql-db:
        image: 'mysql:5.6.45'
        container_name: mysql-db
        command: --max_allowed_packet=2G
        environment:
            MYSQL_ROOT_PASSWORD: MAcri
            MYSQL_DATABASE: apromore
            MYSQL_USER: apromore
            MYSQL_PASSWORD: MAcri
        volumes:
            - "./Supplements/database/mysql-data:/var/lib/mysql"
        ports:
            - "3306"