version: "3.7"
services:
    apromore-dev:
        build:
            context: .
            dockerfile: dockerfile.dev
        image: apromore/apromore:dev
        container_name: apromore-dev
        volumes:
            - ".:/opt/apromore/"
        depends_on:
            - mysql-db   
        ports:
            - "9000:9000"
            
    mysql-db:
        image: 'mysql:5.6.45'
        container_name: mysql-db
        command: --max_allowed_packet=2G
        environment:
            MYSQL_ROOT_PASSWORD: MAcri
            MYSQL_DATABASE: apromore
            MYSQL_USER: apromore
            MYSQL_PASSWORD: MAcri
        volumes:
            - "./Supplements/database/mysql-data:/var/lib/mysql"
        ports:
            - "3306"