version: "3.7"
services:
    apromore:
        build: 
            context: .
            dockerfile: Dockerfile.dev
        image: apromore/apromore:test
        ports:
            - "9000:9000"
        volumes:
            - /opt/apromore/**/target/
            - .:/opt/apromore
            